# Generated by Django 5.2.3 on 2025-07-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='uploads/')),
                ('text_content', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0.0)),
                ('keywords_matched', models.JSONField(default=list)),
            ],
        ),
    ]
