# Generated by Django 5.2.3 on 2025-08-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('extracted_keywords', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('EMAIL', 'Email'), ('ATS', 'ATS')], max_length=10)),
                ('source_details', models.TextField()),
                ('last_fetched', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleKeywordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('keywords', models.JSONField(default=list)),
            ],
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='keywords_matched',
            new_name='matched_keywords',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='text_content',
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
